### PR TITLE
gas test

### PR DESCRIPTION
**Pull request by volovyks**

### CODE REVIEW

**Comment by ailisp** [comment]
Nice finding! I would also test using a maximum sized request

**Comment by volovyks** [comment]
@ailisp what do you mean by maximum sized request? Aren't they all the same size?

**Review by ppca — APPROVED** [review]

**Comment by ailisp** [comment]
@volovyks i mean path. there was some clear_state_on_finish invoked by sign_helper spending around 6T gas while it usually spend 3T gas. Given the clear_state_on_finish is very simple, it maybe related to size of request

**Comment by volovyks** [comment]
@ailisp good point, I've checked, and `path` size does [affect](https://testnet.nearblocks.io/txns/AM7B5Ym4M3Q5uEWN5LKS2ZL91h6f9fjxfXexUSguZ1MG) gas, but it is not significant for now.

**Pull request merged**
