### PR TITLE
Fix decrease request counter fails

### PR DESCRIPTION
**Pull request by ailisp**
Based on analysis on code, it is quite solid and should always decrement the request counter, unless the execution of clear_state_on_finish is fail. This is because:

- we only increase and decrease request counter via helper function `add_request` and `remove_request`, so it's not possible it becomes out of sync to the actual request LookupMap
- `add_request` is only called by `sign_helper`
- `remove_request` is in `clear_state_on_finish`, only in a promise created by `sign_helper` and the promise will be executed by yield_resume.
- yield_resume will either happen by our node calls `respond`, or when timeout (200 blocks), automatically execute by protocol
- `add_request` and the promise creation is atomic, it's not possible `add_request` happens but the promise containing `remove_request` not happens, and the promise is guaranteed to be executed by protocol

Assume protocol yield resume works correctly, the only possibility corresponding remove_request is not executed with add_request is: clear_state_on_finish fails. Looking at its code it can fail two case:
- return err when remove_request does not remove a request due to not exist, this is fine since it doesn't remove anything in pending request. 
- it runs of gas

So we only need to fix it runs out of gas.

An example of this failure: https://testnet.nearblocks.io/txns/BWMiXjpwaKWu9T5RMBR2YvYiAjbYvdpG8j63b8MtWyC6#execution, right after it, required_deposit increased from 1 yocto to 0.05 NEAR, due to pending request increased from 3 to 4: https://testnet.nearblocks.io/txns/DRFLMMXiaXdzDdwU9FY86em7UZPETFNALB9FzsfrBYvm#execution.

Increase the gas used for clear_state_on_finish should be good for future request. To cleaning up, we should clean up the contract LookupMap manually, which required make remove_request a public method, which require deploy a temp contract, or migrate to a new contract account with empty pending requests.

### CODE REVIEW

**Review by volovyks — APPROVED** [review]
Sounds right! Nice work.

**Comment by volovyks** [comment]
@ppca let's make sure we follow these instructions on our next deployment on each env

**Comment by ppca** [comment]
I can try doing the cleanup for our dev contract this week, and I'll do the same for testnet and mainnet on next rc.

**Comment by ppca** [comment]
It seems like init_running will get the job done. Is there any caveat to using init_running? @ailisp

**Comment by ailisp** [comment]
> It seems like init_running will get the job done. Is there any caveat to using init_running? @ailisp

Yeah init_running should work when set up a new contract account. Is there chance that we reuse an account to deploy a new version of contract?

**Comment by ppca** [comment]
yeah we could use init_running to re-init the same account

**Comment by ailisp** [comment]
@ppca I suspect that doesn't clear the content of pending_requests LookupMap. LookupMap stores metadata under trie key `STATE`, but all key value pair is stored separately on trie under key LookupMap prefix + key's borsh serialization.

If the content of LookupMap is not cleared, problems: same request will not be inserted since lookup map find it exists under key `prefix+key borsh`, and we will not be able to process this exact request. Let me check it. Is dev contract v1.signer-dev.testnet? `init_running` is last called a month ago.

**Comment by ailisp** [comment]
So v1.signer-dev.testnet has no pending requests. 
v1.signer-prod.testnet does have pending requests:
```
 near contract view-storage v1.signer-prod.testnet all as-json network-config testnet now
Contract state (values):
[
  {
    "key": "ALGgfqgW1CUHB045TYZ9SG+b2AeCt8zB5ArMiayuTLP8O6oLtdh6qmVBdc3HjoyeEQtj+Wy+bjMA03mFqmRGpAE=",
    "value": "BazmqsPhe+S+ZRX9TvNk7oU2OBbtUFzjZCa+FxJpAos="
  },
  {
    "key": "ALGgfqgW1CUHB045TYZ9SG+b2AeCt8zB5ArMiayuTLP8dL6xmW0w/JmqZQdcJojg7TlpU19uhKFS5hSReWTyQpg=",
    "value": "ILdYtZrtUGM3RI5uAleduAElaukkfETa5+567qiEGsE="
  },
  {
    "key": "ALGgfqgW1CUHB045TYZ9SG+b2AeCt8zB5ArMiayuTLP8zNnF4z94yVqvmsKCydp0KCdwpfn61l+PI6ePaFAz26E=",
    "value": "tk4I70BNAXpBafdMoQwbtkwXyoqvi8TuObtd2EP8BBw="
  },
  {
    "key": "ALGgfqgW1CUHB045TYZ9SG+b2AeCt8zB5ArMiayuTLP8+34l739fyPwwnpDxHm1iOCrUIVXo51dctbIY7bQx7XY=",
    "value": "WOm3cfFqMSlwb2jQtJ/TQsYHMTYJ50eaLJ32Dh3nt/o="
  },
  {
    "key": "AO3wc7+6lwb1SjvhymyBaXkrx7HPnTMrVHZTXOaiVjLLAQwhyVARo704dO0M08UH25Fd9Ngo8Hwk9O7lRUzjJSo=",
    "value": "M1wnEcP4cj6yveCwcu8x0xGZUvwAml/MxnZ/GBWRt78="
  },
  {
    "key": "AO3wc7+6lwb1SjvhymyBaXkrx7HPnTMrVHZTXOaiVjLLadgaXgFfLOzBXTUriVXEuy/ova1EdC/eaXv3vhcmbNo=",
    "value": "o0JCVvgY0MGnC+TNTHNHp999GDTIpM5DRLSmDFy7/dw="
  },
  {
    "key": "AO3wc7+6lwb1SjvhymyBaXkrx7HPnTMrVHZTXOaiVjLLf/hZwSreYmDR6LPp0/VUnsN/eMLNWLbeSbIeBb7g8ZY=",
    "value": "l5BnbNYQw3Nv/U1y3M5SMZm/4SRsedDnMq6xmCnHRiY="
  },
  {
    "key": "U1RBVEU=",
    "value": "AAIAAAAAAAAAAAgAAAAIAAAAGQAAAGF1cm9yYS1tdWx0aWNoYWluLnRlc3RuZXQZAAAAYXVyb3JhLW11bHRpY2hhaW4udGVzdG5ldBIAAABodHRwOi8vMzQuNDkuMjExLjRBlfnZFaQpsLMWe8tKjcd7QF8RuSWgu43NTEQlHGrqfiEAAAAAmylOQFaC2xzvLKEHcbrfQqo4buFiS+fK2cSuO3fL6jQQAAAAYnN0LW5lYXIudGVzdG5ldBAAAABic3QtbmVhci50ZXN0bmV0EgAAAGh0dHA6Ly8zNC45OC45NC43Obr1D+aQsPAWT7uXhZtQv7anXn7JxNHhCOEFZ4zZXpF0IQAAAACOVoL1ZnzmcoUGJwAOSlOj9gaVsgNTOlB2ujNidVtFnhkAAABpbmZzdG9uZXNfbmVhcm1wYy50ZXN0bmV0GQAAAGluZnN0b25lc19uZWFybXBjLnRlc3RuZXQUAAAAaHR0cDovLzM0LjQ5LjI0Ni4xMjVzlfreLzx79M4PQ9GztUbuyagMP0ZgIvt2xj/LjKcAdCEAAAAARkqD1L8hQXB6qxudsdD7bt7vRkYDi4xT8W6Dn/QjTIITAAAAbGlmdGVkLW5lYXIudGVzdG5ldBMAAABsaWZ0ZWQtbmVhci50ZXN0bmV0EwAAAGh0dHA6Ly8zNC40OS41NC4xMDd90ageOaH5Czp28bvnFkBDXHi2X1dwY2MrLkRs+YFDAyEAAAAA2K6DnlVAZHcLY2UnmUxSyJ5X9ALyeODmg0TSL/dbt8kQAAAAbXBjLWxnbnMudGVzdG5ldBAAAABtcGMtbGducy50ZXN0bmV0EwAAAGh0dHA6Ly8zNC40OS4yMzEuNTkI4by5nB0LC+fG7wW4x7GIBiOTru1kTyduJW58Bf70aCEAAAAASiNQg//tsDEtF1c1l7TAdNSQt2SGtY7SDH1rFncCud8fAAAAbmVhci1tcGMtc3Rha2luZzRhbGwtMDEudGVzdG5ldB8AAABuZWFyLW1wYy1zdGFraW5nNGFsbC0wMS50ZXN0bmV0FQAAAGh0dHA6Ly8zNC4xNDQuMTkzLjExMfqKHfbxdfHrnLThIXtlZuNMs8h/8k3boL5pcydmqOloIQAAAABikyMPjphhy3jPwaZig8jHnKTXDebmTIShkX/Lreja3RMAAABub2RlbW9uc3Rlci50ZXN0bmV0EwAAAG5vZGVtb25zdGVyLnRlc3RuZXQVAAAAaHR0cDovLzM0LjEyOC4xMzQuMTM2Nny7fjDRu1hQTV596nRXZ1o4lA9wm6Rtch21pu3HpQchAAAAADtnm+9qgm4tasJY1eM7RyiVuMyoyHNCIx2q4NPA1ICRGQAAAHBhZ29kYS1tdWx0aWNoYWluLnRlc3RuZXQZAAAAcGFnb2RhLW11bHRpY2hhaW4udGVzdG5ldBQAAABodHRwOi8vMzQuMzYuMTU3LjI1M9a/TGs75DCcqnvmTtBjKQUyXF5cCmo++U2YK/WR6f9XIQAAAAD2L2zY3eJdLPcvp5+MocbVlu0HCn3R2jnzomSylQGkHAgAAAAZAAAAYXVyb3JhLW11bHRpY2hhaW4udGVzdG5ldAAAAAAQAAAAYnN0LW5lYXIudGVzdG5ldAEAAAAZAAAAaW5mc3RvbmVzX25lYXJtcGMudGVzdG5ldAIAAAATAAAAbGlmdGVkLW5lYXIudGVzdG5ldAMAAAAQAAAAbXBjLWxnbnMudGVzdG5ldAQAAAAfAAAAbmVhci1tcGMtc3Rha2luZzRhbGwtMDEudGVzdG5ldAUAAAATAAAAbm9kZW1vbnN0ZXIudGVzdG5ldAYAAAAZAAAAcGFnb2RhLW11bHRpY2hhaW4udGVzdG5ldAcAAAAEAAAAAAAAAEEAAAABqLuBdnR2gqq1xoHU7zdcpTcCOysofYtfnYlQUnelopFTjvNoCILY+3k6YqX9tMaXTHzY+esLnLv2WTFMMDRwAAAAAAAAAAAAAAAAAAEAAAAABwAAAAAAAAACAAAAAXYCAAAAAW0AAAAAAAAAAOCTBAAAAAAAAN1tAAAAAAACAAAAQAAAAAAEAAAAAEAAwCcJAAAAAAAAAAAAAAIAAAAAIADIrwAAAAAAAAAAAADIrwAAAAAAAEANAwAAAAAAAFwmBQAAAAAAAAAAAAAAAAAAAAA="
  }
]
```

For all key except ` "key": "U1RBVEU=",` are not cleared pending requests. Let me know when you call init_running on v1.signer-prod.testnet next time! Then we can check whether pending requests are cleared

**Pull request merged**
