### PR TITLE
u128 -> U128 in experimental_signature_deposit

### PR DESCRIPTION
**Pull request by volovyks**

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
Nice!

**Review by bh2smith — APPROVED** [review]
Nice!

**Review by ailisp — APPROVED** [review]
lgtm!

**Comment by ailisp** [comment]
test_experimental_signature_deposit needs to be fixed

**Review by ailisp — APPROVED** [review]

**Comment by bh2smith** [comment]
Has this new contract been deployed to both mainnet and testnet?

**Comment by volovyks** [comment]
@bh2smith only to dev env `v1.signer-dev.testnet`.
`v1.signer-prod.testnet` and `mainnet` will be released with other features later.

**Pull request merged**
