### PR TITLE
chore: make mainnet only have log level INFO where DEBUG is too spammy

### PR DESCRIPTION
**Pull request by ChaoticTempest**

### CODE REVIEW

**Review by ailisp — APPROVED** [review]
looks good to me!

**Comment by ChaoticTempest** [comment]
@kmaus-near @ppca let me know if this is good to go with mainnet release before I merge it

**Comment by ppca** [comment]
I'd prefer keeping DEBUG for now since it might be easier to debug with more information. Like we can ask partners to search their logs and see if they have certain entries to verify if certain things have happened.

**Comment by ChaoticTempest** [comment]
yeah, but mainnet is where prod is supposed to be at. It's not supposed be where we should be debugging... 

But we can keep debug in our mainnet-dev

**Review by ppca — APPROVED** [review]

**Pull request merged**
